refactor out duplicate code
jarkkojs/mmledger pull request #41
Opened 2022-04-02 06:19 UTC by jarkkojs

2022-04-02 06:30 UTC, jarkkojs commented
@npmccallum I did these changes to factor out any possibilities of `mmledger` failing as I'm debugging SGX2. There's also added self-consistency checks in addition to minimizing the code paths.

2022-04-03 11:58 UTC, jarkkojs commented
In SGX we must to pro-actively `mmledger` to detect overlaps because it will be a long time, if ever, we support them, given the complexities, which have to nothing to do with `mmledger` implementation. By dividing the problem like this to nicely encapsulated components, it's easy to make the call to `delete()` optional without messing out the code.

2022-04-06 09:39 UTC, haraldh approved these changes, later dismissed

2022-04-06 14:37 UTC, npmccallum requested changes

2022-04-06 14:37 UTC, npmccallum commented on src/lib.rs
> +        ],
```suggestion
        records: [Record::EMPTY; 5],
```

2022-04-06 22:16 UTC, jarkkojs commented
@npmccallum please review

2022-04-07 06:57 UTC, haraldh approved these changes, later dismissed

2022-04-07 10:21 UTC, jarkkojs commented
@npmccallum mmap PR is not anymore dependent on this but please approve this when you can because it is needed for continuation.

2022-04-07 11:10 UTC, jarkkojs commented
Added snapshot of the Heap to this PR. It can refined from this point forward.

2022-04-07 11:48 UTC, jarkkojs commented
moved heap to a separate branch which i upstream later on

2022-04-07 14:40 UTC, merged